name: GitHub Pages

on:
  push:
    branches:
      # The branch where the project source code resides
      # 项目源代码所在的分支
      - main
      - master
      - valaxy

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Use pnpm and Node.js 24
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true
          install: false

      - name: 📦 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔎 Type Check
        run: pnpm typecheck

      - name: 🌌 Build Valaxy Blog
        run: pnpm build

      - name: 🪤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
